// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_post.sql

package queries

import (
	"context"
)

const delete = `-- name: Delete :one
delete from posts where id = ?

returning id, title, content, category, tags, createdat, updatedat
`

func (q *Queries) Delete(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, delete, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
