// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_blogs_filter.sql

package queries

import (
	"context"
)

const getBlogsFilter = `-- name: GetBlogsFilter :many
select id, title, content, category, tags, createdat, updatedat from blogs 
WHERE title LIKE '%' || ? || '%'
   OR content LIKE '%' || ? || '%'
   OR category LIKE '%' || ? || '%'
`

type GetBlogsFilterParams struct {
	Column1 string
	Column2 string
	Column3 string
}

func (q *Queries) GetBlogsFilter(ctx context.Context, arg GetBlogsFilterParams) ([]Blog, error) {
	rows, err := q.db.QueryContext(ctx, getBlogsFilter, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blog
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.Tags,
			&i.Createdat,
			&i.Updatedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
