// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_blog.sql

package queries

import (
	"context"
)

const getBlog = `-- name: GetBlog :one
select id, content, user_id from blogs where id = ?
`

func (q *Queries) GetBlog(ctx context.Context, id int64) (Blog, error) {
	row := q.db.QueryRowContext(ctx, getBlog, id)
	var i Blog
	err := row.Scan(&i.ID, &i.Content, &i.UserID)
	return i, err
}
