// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_user.sql

package queries

import (
	"context"
	"database/sql"
)

const insertUser = `-- name: InsertUser :one
insert into users(username, password) values(?, ?)

RETURNING id, username, password
`

type InsertUserParams struct {
	Username sql.NullString
	Password sql.NullString
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}
