// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_post.sql

package queries

import (
	"context"
)

const insertPost = `-- name: InsertPost :one
insert into posts(content, title, category, tags, createdAt, updatedAt) values(?, ?, ?, ?, ?, ?)

returning id, title, content, category, tags, createdat, updatedat
`

type InsertPostParams struct {
	Content   string
	Title     string
	Category  string
	Tags      string
	Createdat string
	Updatedat string
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, insertPost,
		arg.Content,
		arg.Title,
		arg.Category,
		arg.Tags,
		arg.Createdat,
		arg.Updatedat,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
