// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_blog.sql

package queries

import (
	"context"
	"database/sql"
)

const insertBlog = `-- name: InsertBlog :one
insert into blogs(content, user_id) values(?, ?)

returning id, content, user_id
`

type InsertBlogParams struct {
	Content sql.NullString
	UserID  sql.NullInt64
}

func (q *Queries) InsertBlog(ctx context.Context, arg InsertBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, insertBlog, arg.Content, arg.UserID)
	var i Blog
	err := row.Scan(&i.ID, &i.Content, &i.UserID)
	return i, err
}
