// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_blog.sql

package queries

import (
	"context"
)

const insertBlog = `-- name: InsertBlog :one
insert into blogs(content, title, category, tags, createdAt, updatedAt) values(?, ?, ?, ?, ?, ?)

returning id, title, content, category, tags, createdat, updatedat
`

type InsertBlogParams struct {
	Content   string
	Title     string
	Category  string
	Tags      string
	Createdat string
	Updatedat string
}

func (q *Queries) InsertBlog(ctx context.Context, arg InsertBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, insertBlog,
		arg.Content,
		arg.Title,
		arg.Category,
		arg.Tags,
		arg.Createdat,
		arg.Updatedat,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
