// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Blog struct {
	ID      int64
	Content sql.NullString
	UserID  sql.NullInt64
}

type User struct {
	ID       int64
	Username sql.NullString
	Password sql.NullString
}
