// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

type Post struct {
	ID        int64
	Title     string
	Content   string
	Category  string
	Tags      string
	Createdat string
	Updatedat string
}
