// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_blog.sql

package queries

import (
	"context"
	"database/sql"
)

const updateBlog = `-- name: UpdateBlog :one
update blogs set content = ? where id = ?

returning id, content, user_id
`

type UpdateBlogParams struct {
	Content sql.NullString
	ID      int64
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, updateBlog, arg.Content, arg.ID)
	var i Blog
	err := row.Scan(&i.ID, &i.Content, &i.UserID)
	return i, err
}
