// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_blog.sql

package queries

import (
	"context"
)

const updateBlog = `-- name: UpdateBlog :one
update blogs set content = ?, title = ?, tags = ?, updatedat = ?  where id = ?

returning id, title, content, category, tags, createdat, updatedat
`

type UpdateBlogParams struct {
	Content   string
	Title     string
	Tags      string
	Updatedat string
	ID        int64
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.db.QueryRowContext(ctx, updateBlog,
		arg.Content,
		arg.Title,
		arg.Tags,
		arg.Updatedat,
		arg.ID,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
