// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_post.sql

package queries

import (
	"context"
)

const updatePost = `-- name: UpdatePost :one
update posts set content = ?, title = ?, tags = ?, category = ?, updatedat = ?  where id = ?

returning id, title, content, category, tags, createdat, updatedat
`

type UpdatePostParams struct {
	Content   string
	Title     string
	Tags      string
	Category  string
	Updatedat string
	ID        int64
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.Content,
		arg.Title,
		arg.Tags,
		arg.Category,
		arg.Updatedat,
		arg.ID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.Tags,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
